Change pin email format and added gettext
wintermeyer/animina pull request #1133
Opened 2024-11-08 07:16 UTC by MICHAELMUNAVU83

2024-11-08 10:36 UTC, wintermeyer requested changes
Please remove those duplicate empty lines. Just one empty line is plenty. And indent the PIN by 4 spaces.

<img width="796" alt="Bildschirmfoto 2024-11-08 um 11 18 10" src="https://github.com/user-attachments/assets/4744dd66-7a3d-4009-94fd-8bac2a925b09">

2024-11-08 10:36 UTC, wintermeyer commented on .tool-versions
> +erlang 24.1.1
Why do we downgrade Erlang here?

2024-11-11 05:07 UTC, MICHAELMUNAVU83 commented on .tool-versions
> +erlang 24.1.1
Aah my bad , let me remove this

2024-11-11 05:32 UTC, MICHAELMUNAVU83 commented
I now have it as such
![Screenshot 2024-11-11 at 08 30 41](https://github.com/user-attachments/assets/58e1b978-2cfd-45f8-8b30-0564534640cc)

I have tried the pin indentation and it does not seem to work , we can have it as a seperate issue .

2024-11-11 08:50 UTC, wintermeyer approved these changes

2024-11-11 08:50 UTC, merged

2024-11-11 08:51 UTC, wintermeyer commented
@MICHAELMUNAVU83 I just triggered a deployment. Please test it in 10-15 minutes on production.

2024-11-11 11:22 UTC, MICHAELMUNAVU83 commented
It is now as such
![Screenshot 2024-11-11 at 14 16 21](https://github.com/user-attachments/assets/8fd9ed38-2bc6-448a-9735-868aa3be24ae)