add kamal config, closes #1169
wintermeyer/animina pull request #1170
Opened 2024-11-26 03:40 UTC by briankariuki

2024-12-02 07:07 UTC, wintermeyer requested changes
Please add a `demo` environment. See https://github.com/animina-dating/animina/issues/1173

Please double check that we can run both environments on the same server without them interfering with each other. I don't want the `demo` environment deleting images from `production` and vice versa. Same with the database.

And please send @wintermeyer an email which outlines the move from the current production to the new system. Does anything have to be moved for that on the production system?

2024-12-02 07:07 UTC, wintermeyer commented on lib/animina_web/plugs/health_check.ex
> +  def call(%{path_info: ["up"]} = conn, _opts) do
Did you add `up` on the blacklist for usernames? If not: Please do.

2024-12-02 09:38 UTC, briankariuki commented on lib/animina_web/plugs/health_check.ex
> +  def call(%{path_info: ["up"]} = conn, _opts) do
I've added it to the list of bad usernames

2024-12-02 09:39 UTC, briankariuki commented
> Please double check that we can run both environments on the same server without them interfering with each other. I don't want the `demo` environment deleting images from `production` and vice versa. Same with the database.
> 

So long as each instance is mapped to its own database, port and file volume, there will be no issues.

2024-12-02 12:47 UTC, wintermeyer commented
@briankariuki The tests failed. Please check.

2024-12-03 08:10 UTC, wintermeyer approved these changes

2024-12-03 08:10 UTC, merged