Added a new route and template for the first 4 fields
wintermeyer/animina pull request #1176
Opened 2024-11-29 05:58 UTC by MICHAELMUNAVU83

- I added "beta" as a bad username and created a route "/beta" for the new registation workflow , it has the 4 initial fields we use ,Date of Birth , Zip Code , Gender and  Height  .
![Screenshot 2024-11-29 at 08 53 45](https://github.com/user-attachments/assets/16e0214c-5f57-4e34-a67d-475ad78ad18e)

2024-11-29 08:31 UTC, wintermeyer requested changes
<img width="1139" alt="Bildschirmfoto 2024-11-29 um 09 18 21" src="https://github.com/user-attachments/assets/558563a1-d95c-4104-8201-5c9ecc4447af">

## Thoughts

- For what ever reason the birthdate field is a constant source of trouble. Our users have problems to enter dates which are > 20 years ago. It seems to be easier for them to just enter a date as a text. We have to convert that into a date. And we have to make sure that the input makes sense. Input examples: "20.12.1970", "20.12.70", "20.12.01", "20.12.2000". What doesn't work: "20.12." (that would through a validation error).
- Let us start with a `"<h2>Your future partner</h2>"` section which asks for the gender. I know that I wanted to start with the user's gender first. But this way it makes more sense. After that we do a `"<h2>About you</h2>"` section where we ask the data from the user.

2024-11-29 08:31 UTC, wintermeyer commented on lib/animina/validations/bad_username.ex
> +    bad_usernames = ["my", "current_user", "profile", "beta"]
+ ["test", "new", "alpha", "next", "Stefan", "Stephan", "Aurelius", "Juna", "Miri", "Miriam", "aw", "jw", "sw"]

2024-11-29 08:31 UTC, wintermeyer commented on lib/animina/validations/bad_username.ex
>      if username &&
While we are at it: Please add a validation, that a username has to have at least 2 characters.

2024-11-29 08:37 UTC, MICHAELMUNAVU83 commented
I also think we need to remove zip codes , or do Germans know exact zipcodes , If a zipcode is 56083 , that means I have to type in all 5 numbers to see a result , what are your thoughts?

2024-11-29 08:39 UTC, wintermeyer commented
> I also think we need to remove zip codes , or do Germans know exact zipcodes , If a zipcode is 56083 , that means I have to type in all 5 numbers to see a result , what are your thoughts?

Good thinking! But Germans do know their zip code. And yes, the user has to enter all 5 digits.

2024-11-29 11:38 UTC, MICHAELMUNAVU83 commented
@wintermeyer  , one question , do you want it to be a 2 step page that is.
Step 1.
Select Gender and the zip code and see the number of potential partners , then hit proceed to go to the next stage/page or have them all in one oage , with a title under each so we have

1. Future Partner Information
2. Info about you
3. Then now the whole data page with email , username etc

2024-11-29 13:15 UTC, wintermeyer commented
> @wintermeyer , one question , do you want it to be a 2 step page that is. Step 1. Select Gender and the zip code and see the number of potential partners , then hit proceed to go to the next stage/page or have them all in one oage , with a title under each so we have
> 
> 1. Future Partner Information
> 2. Info about you
> 3. Then now the whole data page with email , username etc

One page with all the information until the flags but without the user and password info. Then a new page with the user and password thing. PIN. Then flags. Then about me story.

2024-11-30 06:51 UTC, MICHAELMUNAVU83 commented
@wintermeyer  kindly confirm if this layout is now okay

![Screenshot 2024-11-30 at 09 47 36](https://github.com/user-attachments/assets/51d6de03-5bc3-4ea8-a48f-75cf18cb3133)

2024-11-30 06:54 UTC, MICHAELMUNAVU83 commented
And also does this new layout mean that if someone selects a partners gender as male , we automatically have their gender as female and so on?

2024-11-30 07:54 UTC, wintermeyer commented
> @wintermeyer kindly confirm if this layout is now okay

The basic layout is ok. But the fields are not. Please ask youself "What information do we need to narrow down the potential partner?"  Those are the fields we are asking for on this very first page. Not `username` because that doesn't narrow down the search. Please add the things which narrow down the search from the second page to this page too.

We only ask for the birthdate and the height because that helps us to refill other fields automatically. Therefor it helps us to narrow down the search. But the `occupation` doesn't help us here.

<img width="805" alt="Bildschirmfoto 2024-11-30 um 08 49 05" src="https://github.com/user-attachments/assets/0d87fb40-fb79-4263-b6b7-dd373228b979">

2024-11-30 07:55 UTC, wintermeyer commented
> And also does this new layout mean that if someone selects a partners gender as male , we automatically have their gender as female and so on?

Yes, we do use this information to make a guess about the gender of the user. But just to prefill that form field. The user can override it.

2024-11-30 08:30 UTC, MICHAELMUNAVU83 commented
![Screenshot 2024-11-30 at 11 29 09](https://github.com/user-attachments/assets/178e71ef-cafa-4228-b34f-3a8af528320d)


I have removed the other fields , we now have it as such

2024-11-30 09:21 UTC, wintermeyer commented
> I have removed the other fields , we now have it as such @wintermeyer

Very well. Now add these field to the same form.

<img width="1096" alt="Bildschirmfoto 2024-11-30 um 10 20 26" src="https://github.com/user-attachments/assets/3b929fcf-6a18-42ec-a2c6-5d10bba8ceb7">

2024-11-30 09:32 UTC, MICHAELMUNAVU83 commented
Should this be under the "Future Partner Information" section or  "Information about you" part @wintermeyer

2024-11-30 09:33 UTC, wintermeyer commented
> Should this be under the "Future Partner Information" section or "Information about you" part @wintermeyer

For now: Add an other "Future Partner Information" section below the current "Information about you" one. We'll figure out the design later. I want a workflow which narrows down the list of potential partners. A sort of funnel.

2024-11-30 09:42 UTC, MICHAELMUNAVU83 commented
Like this ? @wintermeyer 

<img width="1440" alt="Screenshot 2024-11-30 at 12 36 49" src="https://github.com/user-attachments/assets/79150717-d9ca-45d9-b784-0941fafffe3b">
<img width="1440" alt="Screenshot 2024-11-30 at 12 36 43" src="https://github.com/user-attachments/assets/3e8155c8-8a5a-4466-8b8d-457d76a8a120">

2024-11-30 09:45 UTC, wintermeyer commented
> Like this ? @wintermeyer

Yes! But please reorder to this order:

- Height
- Birthdate
- ZipCode

Why? That gives us a couple of more milliseconds to pre-fill the values below. So when somebody enters the `height` we calculate the default values for the min and max partner height. Same with the age. Of course the user can override it but a lot of people will not and for them it is a real help and usability improvement.

2024-11-30 09:50 UTC, MICHAELMUNAVU83 commented
That does make sense 
<img width="1440" alt="Screenshot 2024-11-30 at 12 47 43" src="https://github.com/user-attachments/assets/a7fcba7d-6154-4eed-8033-60f7893a7252">


Also advice on how we should have defaults for heights , can we do +- 20 centimeters and for age +- 5 years?

2024-11-30 09:51 UTC, wintermeyer commented
> Also advice on how we should have defaults for heights , can we do +- 20 centimeters and for age +- 5 years?

Yes, those values make sense. And as always: Should be config variables which an admin can change in config.exs, dev.exs, test.exs or prod.exs and not manually in the hardcodes LiveView code.

2024-11-30 09:54 UTC, MICHAELMUNAVU83 commented
Okay , we can merge this , then I can work on the potential partner algorithm

2024-11-30 09:55 UTC, wintermeyer approved these changes

2024-11-30 09:55 UTC, merged