playing around with the demo
wintermeyer/animina pull request #7
Opened 2024-01-22 14:23 UTC by philipp-kempgen

2024-01-22 15:32 UTC, wintermeyer requested changes
Please have a look into the `./setup-hooks.sh` to see what needs to be done before a git commit.

2024-01-22 15:32 UTC, wintermeyer commented on lib/animina_web/components/animina_components.ex
Please run `mix format` before committing it.
  
  Code Readability                                                              
┃ 
┃ [R] ↘ There should be no trailing white-space at the end of a line.
┃       lib/animina_web/components/animina_components.ex:265:1 #(AniminaWeb.AniminaComponents.humanized_points)
┃ [R] ↘ There should be no trailing white-space at the end of a line.
┃       lib/animina_web/components/animina_components.ex:253:1 #(AniminaWeb.AniminaComponents.status_bar)
┃ [R] ↘ There should be no trailing white-space at the end of a line.
┃       lib/animina_web/components/animina_components.ex:251:1 #(AniminaWeb.AniminaComponents.status_bar)

2024-01-24 18:27 UTC, philipp-kempgen commented on lib/animina_web/components/animina_components.ex
"`mix credo --strict`" läuft jetzt durch.

2024-01-24 18:28 UTC, wintermeyer approved these changes

2024-01-24 18:29 UTC, merged