phototags resource
wintermeyer/animina pull request #987
Opened 2024-08-30 08:19 UTC by Kimutai01

I decided to break the task into parts.
I created a phototag resource with a description, user and photo
You can check and advice 
Should I add a relation to a flag?

2024-08-30 09:12 UTC, wintermeyer requested changes
Please replace `Tag` with `Flag`. My bad! Sorry!

It doesn't make sense to have too different words for the same thing in one application.

2024-09-02 17:07 UTC, Kimutai01 commented
@wintermeyer I have updated the resource to PhotoFlagTags 
I have also added the relation to a flag

2024-09-02 17:29 UTC, wintermeyer requested changes
Please rename the resource to `PhotoFlags`. Keep it simple. And please don't forget to rename the file names too. That resource e.g. was still in `photo_tags.ex`.

2024-09-02 18:48 UTC, wintermeyer approved these changes

2024-09-02 18:48 UTC, merged